=== RedDTG/mcu-flowchart/dataset/schemas/media.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Marvel Media",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "title",
    "release_date",
    "universe",
    "summary",
    "mediatype",
    "poster",
    "connections"
  ],
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "release_date": {
      "type": "string",
      "format": "date"
    },
    "end_date": {
      "type": ["string", "null"],
      "format": "date"
    },
    "saga": {
      "type": "string",
      "minLength": 1
    },
    "phase": {
      "type": ["integer", "null"]
    },
    "universe": {
      "type": "string",
      "enum": [
        "mcu",
        "marvel-television",
        "fox-marvel-cinematic-universe",
        "sonys-spider-man-universe",
        "columbia-pictures",
        "new-line-cinema",
        "netflix"
      ]
    },
    "mediatype": {
      "type": "string",
      "enum": ["movie", "show", "special"]
    },
    "poster": {
      "type": "string",
      "minLength": 1
    },
    "summary": {
      "type": "string",
      "minLength": 1
    },
    "connections": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "required",
        "optional",
        "references"
      ],
      "properties": {
        "required": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/connection"
          }
        },
        "optional": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/connection"
          }
        },
        "references": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/connection"
          }
        }
      }
    }
  },
  "$defs": {
    "connection": {
      "type": "object",
      "additionalProperties": false,
      "oneOf": [
        {
          "required": [
            "media_id"
          ]
        },
        {
          "required": [
            "saga_id"
          ]
        }
      ],
      "properties": {
        "media_id": {
          "type": "string",
          "minLength": 1
        },
        "saga_id": {
          "type": "string",
          "minLength": 1
        },
        "reason": {
          "type": "string"
        },
        "importance": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        }
      }
    }
  }
}

=== RedDTG/mcu-flowchart/dataset/data/media/modok.json
{
    "id": "modok",
    "title": "M.O.D.O.K.",
    "release_date": "2021-05-21",
    "end_date": "2021-05-21",
    "mediatype": "show",
    "poster": "/posters/modok.jpg",
    "summary": "TODO",
    "connections": {
        "required": [],
        "optional": [],
        "references": []
    },
    "universe": "marvel-television"
}

=== RedDTG/mcu-flowchart/dataset/data/media/fantastic-four-2005.json
{
    "id": "fantastic-four-2005",
    "title": "Fantastic Four",
    "release_date": "2005-07-08",
    "saga": "fantastic-four-saga",
    "mediatype": "movie",
    "poster": "/posters/fantastic-four-2005.jpg",
    "summary": "A group of astronauts gain superpowers after a cosmic radiation exposure and must use them to oppose the plans of their enemy, Doctor Victor Von Doom. (source: IMDb)",
    "connections": {
        "required": [],
        "optional": [],
        "references": []
    },
    "universe": "fox-marvel-cinematic-universe"
}

=== RedDTG/mcu-flowchart/dataset/data/media/spider-noir.json
{
    "id": "spider-noir",
    "title": "Spider-Noir",
    "release_date": "2026-05-27",
    "end_date": "2026-05-27",
    "mediatype": "show",
    "poster": "/posters/spider-noir.jpg",
    "saga": "animated-spider-verse",
    "summary": "An aging and down on his luck private investigator in 1930s New York is forced to grapple with his past life as the city's one and only superhero. (source: IMDb)",
    "connections": {
        "required": [],
        "optional": [
            {
                "media_id": "spider-man-into-the-spider-verse"
            }
        ],
        "references": []
    },
    "universe": "sonys-spider-man-universe"
}

=== RedDTG/mcu-flowchart/dataset/data/media/ant-man-and-the-wasp.json
{
    "id": "ant-man-and-the-wasp",
    "title": "Ant-Man and the Wasp",
    "release_date": "2018-07-06",
    "saga": "infinite-saga",
    "phase": 3,
    "mediatype": "movie",
    "poster": "/posters/ant-man-and-the-wasp.jpg",
    "summary": "As Scott Lang balances being both a superhero and a father, Hope van Dyne and Dr. Hank Pym present an urgent new mission that finds the Ant-Man fighting alongside The Wasp to uncover secrets from their past. (source: IMDb)",
    "connections": {
        "required": [
            {
                "media_id": "captain-america-civil-war"
            }
        ],
        "optional": [],
        "references": []
    },
    "universe": "mcu"
}

=== RedDTG/mcu-flowchart/dataset/data/media/spider-man-beyond-the-spider-verse.json
{
    "id": "spider-man-beyond-the-spider-verse",
    "title": "Spider-Man: Beyond the Spider-Verse",
    "release_date": "2027-06-04",
    "saga": "animated-spider-verse",
    "mediatype": "movie",
    "poster": "/posters/spider-man-beyond-the-spider-verse.jpg",
    "summary": "TODO",
    "connections": {
        "required": [
            {
                "media_id": "spider-man-across-the-spider-verse"
            }
        ],
        "optional": [],
        "references": []
    },
    "universe": "sonys-spider-man-universe"
}

=== RedDTG/mcu-flowchart/dataset/data/media/daredevil-born-again-season-2.json
{
    "id": "daredevil-born-again-season-2",
    "title": "Daredevil: Born Again Season 2",
    "release_date": "2026-03-24",
    "end_date": "2026-05-05",
    "saga": "multiverse-saga",
    "phase": 5,
    "mediatype": "show",
    "poster": "/posters/daredevil-born-again-season-2.jpg",
    "summary": "Matt Murdock finds himself on a collision course with Wilson Fisk when their past identities begin to emerge. (source: IMDb)",
    "connections": {
        "required": [
            {
                "media_id": "daredevil-born-again"
            }
        ],
        "optional": [],
        "references": []
    },
    "universe": "mcu"
}

=== RedDTG/mcu-flowchart/dataset/data/media/doctor-strange.json
{
    "id": "doctor-strange",
    "title": "Doctor Strange",
    "release_date": "2016-11-04",
    "saga": "infinite-saga",
    "mediatype": "movie",
    "poster": "/posters/doctor-strange.jpg",
    "summary": "While on a journey of physical and spiritual healing, a brilliant neurosurgeon is drawn into the world of the mystic arts.",
    "connections": {
        "required": [],
        "optional": [],
        "references": []
    },
    "universe": "mcu"
}

=== RedDTG/mcu-flowchart/dataset/data/media/x-men-days-of-future-past.json
{
    "id": "x-men-days-of-future-past",
    "title": "X-Men: Days of Future Past",
    "release_date": "2014-05-23",
    "saga": "x-men-prequel",
    "mediatype": "movie",
    "poster": "/posters/x-men-days-of-future-past.jpg",
    "summary": "TODO",
    "connections": {
        "required": [
            {
                "media_id": "x-men-first-class"
            }
        ],
        "optional": [],
        "references": []
    },
    "universe": "fox-marvel-cinematic-universe"
}
