=== RedDTG/mcu-flowchart/dataset/schemas/media.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Marvel Media",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "title",
    "release_date",
    "universe",
    "summary",
    "mediatype",
    "poster",
    "connections"
  ],
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "release_date": {
      "type": "string",
      "format": "date"
    },
    "end_date": {
      "type": ["string", "null"],
      "format": "date"
    },
    "saga": {
      "type": "string",
      "minLength": 1
    },
    "phase": {
      "type": ["integer", "null"]
    },
    "universe": {
      "type": "string",
      "enum": [
        "mcu",
        "marvel-television",
        "fox-marvel-cinematic-universe",
        "sonys-spider-man-universe",
        "columbia-pictures",
        "new-line-cinema",
        "netflix"
      ]
    },
    "mediatype": {
      "type": "string",
      "enum": ["movie", "show", "special"]
    },
    "poster": {
      "type": "string",
      "minLength": 1
    },
    "summary": {
      "type": "string",
      "minLength": 1
    },
    "connections": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "required",
        "optional",
        "references"
      ],
      "properties": {
        "required": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/connection"
          }
        },
        "optional": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/connection"
          }
        },
        "references": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/connection"
          }
        }
      }
    }
  },
  "$defs": {
    "connection": {
      "type": "object",
      "additionalProperties": false,
      "oneOf": [
        {
          "required": [
            "media_id"
          ]
        },
        {
          "required": [
            "saga_id"
          ]
        }
      ],
      "properties": {
        "media_id": {
          "type": "string",
          "minLength": 1
        },
        "saga_id": {
          "type": "string",
          "minLength": 1
        },
        "reason": {
          "type": "string"
        },
        "importance": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        }
      }
    }
  }
}

=== RedDTG/mcu-flowchart/dataset/data/media/deadpool.json
{
    "id": "deadpool",
    "title": "Deadpool",
    "release_date": "2016-02-12",
    "saga": "deadpool-saga",
    "mediatype": "movie",
    "poster": "/posters/deadpool.jpg",
    "summary": "TODO",
    "connections": {
        "required": [],
        "optional": [],
        "references": [
            {
                "saga_id": "x-men-original-trilogy"
            }
        ]
    },
    "universe": "fox-marvel-cinematic-universe"
}

=== RedDTG/mcu-flowchart/dataset/data/media/logan.json
{
    "id": "logan",
    "title": "Logan",
    "release_date": "2017-03-03",
    "saga": "wolverine-trilogy",
    "mediatype": "movie",
    "poster": "/posters/logan.jpg",
    "summary": "TODO",
    "connections": {
        "required": [],
        "optional": [
            {
                "saga_id": "x-men-original-trilogy"
            }
        ],
        "references": [
            {
                "media_id": "the-wolverine"
            }
        ]
    },
    "universe": "fox-marvel-cinematic-universe"
}

=== RedDTG/mcu-flowchart/dataset/data/media/daredevil-season-2.json
{
    "id": "daredevil-season-2",
    "title": "Daredevil Season 2",
    "release_date": "2016-03-18",
    "end_date": "2016-03-18",
    "saga": "defenders-saga",
    "mediatype": "show",
    "poster": "/posters/daredevil-season-2.jpg",
    "summary": "A blind lawyer by day, vigilante by night. Matt Murdock fights the crime of New York as Daredevil. (source: IMDb)",
    "connections": {
        "required": [
            {
                "media_id": "daredevil-season-1"
            }
        ],
        "optional": [],
        "references": []
    },
    "universe": "netflix"
}

=== RedDTG/mcu-flowchart/dataset/data/media/avengers-doomsday.json
{
  "id": "avengers-doomsday",
  "title": "Avengers: Doomsday",
  "release_date": "2026-12-18",
  "saga": "multiverse-saga",
  "mediatype": "movie",
  "poster": "/posters/avengers-doomsday.jpg",
  "summary": "TODO",
  "connections": {
    "required": [],
    "optional": [],
    "references": []
  },
  "universe": "mcu"
}

=== RedDTG/mcu-flowchart/dataset/data/media/the-fantastic-four-first-steps.json
{
  "id": "the-fantastic-four-first-steps",
  "title": "The Fantastic Four: First Steps",
  "release_date": "2025-07-25",
  "saga": "multiverse-saga",
  "phase": 5,
  "mediatype": "movie",
  "poster": "/posters/the-fantastic-four-first-steps.jpg",
  "summary": "Forced to balance their roles as heroes with the strength of their family bond, the Fantastic Four must defend Earth from a ravenous space god called Galactus and his enigmatic herald, the Silver Surfer. (source: IMDb)",
  "connections": {
    "required": [],
    "optional": [],
    "references": [
      {
        "saga_id": "fantastic-four-saga"
      }
    ]
  },
  "universe": "mcu"
}

=== RedDTG/mcu-flowchart/dataset/data/media/hawkeye.json
{
    "id": "hawkeye",
    "title": "Hawkeye",
    "release_date": "2021-11-24",
    "end_date": "2021-11-24",
    "saga": "multiverse-saga",
    "phase": 4,
    "mediatype": "show",
    "poster": "/posters/hawkeye.jpg",
    "summary": "Clint Barton aka Hawkeye has the mission to get back to his family for Christmas. But when a threat from his past shows up, Hawkeye reluctantly teams up with Kate Bishop, a skilled archer and his biggest fan, to unravel a conspiracy. (source: IMDb)",
    "connections": {
        "required": [
            {
                "media_id": "the-falcon-and-the-winter-soldier"
            },
            {
                "media_id": "black-widow"
            }
        ],
        "optional": [],
        "references": []
    },
    "universe": "mcu"
}

=== RedDTG/mcu-flowchart/dataset/data/media/loki-season-1.json
{
    "id": "loki-season-1",
    "title": "Loki (Season 1)",
    "release_date": "2021-06-09",
    "end_date": "2021-06-09",
    "saga": "multiverse-saga",
    "mediatype": "show",
    "poster": "/posters/loki-season-1.jpg",
    "summary": "TODO",
    "connections": {
        "required": [
            {
                "media_id": "avengers-endgame"
            }
        ],
        "optional": [],
        "references": []
    },
    "universe": "mcu"
}

=== RedDTG/mcu-flowchart/dataset/data/media/x-men-dark-phoenix.json
{
    "id": "x-men-dark-phoenix",
    "title": "X-Men: Dark Phoenix",
    "release_date": "2019-06-07",
    "saga": "x-men-prequel",
    "mediatype": "movie",
    "poster": "/posters/x-men-dark-phoenix.jpg",
    "summary": "Jean Grey begins to develop incredible powers that corrupt and turn her into a Dark Phoenix, causing the X-Men to have to decide if her life is worth more than all of humanity. (source: IMDb)",
    "connections": {
        "required": [
            {
                "media_id": "x-men-apocalypse"
            }
        ],
        "optional": [

        ],
        "references": []
    },
    "universe": "fox-marvel-cinematic-universe"
}
