=== RedDTG/mcu-flowchart/dataset/schemas/media.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Marvel Media",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "title",
    "release_date",
    "universe",
    "summary",
    "mediatype",
    "poster",
    "connections"
  ],
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1
    },
    "title": {
      "type": "string",
      "minLength": 1
    },
    "release_date": {
      "type": "string",
      "format": "date"
    },
    "end_date": {
      "type": ["string", "null"],
      "format": "date"
    },
    "saga": {
      "type": "string",
      "minLength": 1
    },
    "phase": {
      "type": ["integer", "null"]
    },
    "universe": {
      "type": "string",
      "enum": [
        "mcu",
        "marvel-television",
        "fox-marvel-cinematic-universe",
        "sonys-spider-man-universe",
        "columbia-pictures",
        "new-line-cinema",
        "netflix"
      ]
    },
    "mediatype": {
      "type": "string",
      "enum": ["movie", "show", "special"]
    },
    "poster": {
      "type": "string",
      "minLength": 1
    },
    "summary": {
      "type": "string",
      "minLength": 1
    },
    "connections": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "required",
        "optional",
        "references"
      ],
      "properties": {
        "required": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/connection"
          }
        },
        "optional": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/connection"
          }
        },
        "references": {
          "type": "array",
          "items": {
            "$ref": "#/$defs/connection"
          }
        }
      }
    }
  },
  "$defs": {
    "connection": {
      "type": "object",
      "additionalProperties": false,
      "oneOf": [
        {
          "required": [
            "media_id"
          ]
        },
        {
          "required": [
            "saga_id"
          ]
        }
      ],
      "properties": {
        "media_id": {
          "type": "string",
          "minLength": 1
        },
        "saga_id": {
          "type": "string",
          "minLength": 1
        },
        "reason": {
          "type": "string"
        },
        "importance": {
          "type": "number",
          "minimum": 0,
          "maximum": 1
        }
      }
    }
  }
}

=== RedDTG/mcu-flowchart/dataset/data/media/ironheart.json
{
    "id": "ironheart",
    "title": "Ironheart",
    "release_date": "2025-06-24",
    "end_date": "2025-06-24",
    "saga": "multiverse-saga",
    "mediatype": "show",
    "poster": "/posters/ironheart.jpg",
    "summary": "TODO",
    "connections": {
        "required": [
            {
                "media_id": "black-panther-wakanda-forever"
            }
        ],
        "optional": [],
        "references": []
    },
    "universe": "mcu"
}

=== RedDTG/mcu-flowchart/dataset/data/media/jessica-jones-season-2.json
{
    "id": "jessica-jones-season-2",
    "title": "Jessica Jones Season 2",
    "release_date": "2018-03-08",
    "end_date": "2018-03-08",
    "saga": "defenders-saga",
    "mediatype": "show",
    "poster": "/posters/jessica-jones-season-2.jpg",
    "summary": "Following the tragic end of her brief superhero career, Jessica Jones tries to rebuild her life as a private investigator, dealing with cases involving people with remarkable abilities in New York City. (source: IMDB)",
    "connections": {
        "required": [
            {
                "media_id": "defenders"
            }
        ],
        "optional": [],
        "references": []
    },
    "universe": "netflix"
}

=== RedDTG/mcu-flowchart/dataset/data/media/iron-man.json
{
    "id": "iron-man",
    "title": "Iron Man",
    "release_date": "2008-05-02",
    "saga": "infinite-saga",
    "phase": 1,
    "mediatype": "movie",
    "poster": "/posters/iron-man.jpg",
    "summary": "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil. (source: IMDb)",
    "connections": {
        "required": [],
        "optional": [],
        "references": []
    },
    "universe": "mcu"
}

=== RedDTG/mcu-flowchart/dataset/data/media/the-marvels.json
{
  "id": "the-marvels",
  "title": "The Marvels",
  "release_date": "2023-11-10",
  "saga": "multiverse-saga",
  "mediatype": "movie",
  "poster": "/posters/the-marvels.jpg",
  "summary": "Carol Danvers gets her powers entangled with those of Kamala Khan and Monica Rambeau, forcing them to work together to save the universe. (source: IMDb)",
  "connections": {
    "required": [
      {
        "media_id": "ms-marvel"
      },
      {
        "media_id": "wandavision"
      }
    ],
    "optional": [],
    "references": []
  },
  "universe": "mcu"
}

=== RedDTG/mcu-flowchart/dataset/data/media/spider-man-brand-new-day.json
{
  "id": "spider-man-brand-new-day",
  "title": "Spider-Man: Brand New Day",
  "release_date": "2026-07-31",
  "saga": "multiverse-saga",
  "mediatype": "movie",
  "poster": "/posters/spider-man-brand-new-day.jpg",
  "summary": "TODO",
  "connections": {
    "required": [
      {
        "media_id": "spider-man-no-way-home"
      }
    ],
    "optional": [],
    "references": []
  },
  "universe": "mcu"
}

=== RedDTG/mcu-flowchart/dataset/data/media/spider-man.json
{
    "id": "spider-man",
    "title": "Spider-Man",
    "release_date": "2002-05-03",
    "mediatype": "movie",
    "poster": "/posters/spider-man-2002.jpg",
    "saga": "raimi-trilogy",
    "summary": "TODO",
    "connections": {
        "required": [],
        "optional": [],
        "references": []
    },
    "universe": "columbia-pictures"
}

=== RedDTG/mcu-flowchart/dataset/data/media/i-am-groot-season-2.json
{
    "id": "i-am-groot-season-2",
    "title": "I Am Groot (Season 2)",
    "release_date": "2023-09-06",
    "end_date": "2023-09-06",
    "saga": "multiverse-saga",
    "phase": 5,
    "mediatype": "show",
    "poster": "/posters/i-am-groot-season-2.jpg",
    "summary": "A series of shorts featuring the seedling Groot along with several new and unusual characters. (source: IMDb)",
    "connections": {
        "required": [
            {
                "media_id": "i-am-groot-season-1"
            }
        ],
        "optional": [],
        "references": []
    },
    "universe": "mcu"
}

=== RedDTG/mcu-flowchart/dataset/data/media/the-guardians-of-the-galaxy-holiday-special.json
{
    "id": "the-guardians-of-the-galaxy-holiday-special",
    "title": "The Guardians of the Galaxy Holiday Special",
    "release_date": "2022-11-25",
    "saga": "multiverse-saga",
    "mediatype": "special",
    "poster": "/posters/the-guardians-of-the-galaxy-holiday-special.jpg",
    "summary": "Star-Lord, Drax, Rocket, Mantis, and Groot engage in some spirited shenanigans in an all-new original special created for Disney+. (source: IMDb)",
    "connections": {
        "required": [],
        "optional": [],
        "references": []
    },
    "universe": "mcu"
}
